name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    name: Code Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}
          submodules: false
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          debug: true
          base_url: "https://openrouter.ai/api/v1"
          use_file_content: false
          summary_model: |
            openrouter/deepseek/deepseek-chat-v3-0324:free
          model: |
            openrouter/deepseek/deepseek-chat-v3-0324:free
          file_type_prompts: |
            javascript: |
              Focus on ES6+ best practices and modern JavaScript patterns.
              Check for proper async/await usage and error handling.
              Verify performance optimizations and security considerations.
              Look for potential memory leaks and proper event listener cleanup.
            typescript: |
              Focus on type safety and TypeScript best practices.
              Check for proper interface definitions and generic usage.
              Verify strict mode compliance and null safety.
              Look for proper use of utility types and mapped types.
          language: "japanese"
